### ISSUE TITLE
error when calling useContractFunction in useStateToken.tsx

### ISSUE THREAD

**Issue by kavish6** [PatrickAlphaC/defi-stake-yield-brownie-freecode#1]
when I use this useContractFunction in useStateToken.tsx file 
`const {state:approveErc20State,send:approveErc20Send}= useContractFunction(erc20Contract,'approve',{transactionName:"Approve ERC20 transfer"})` **This line**
I got an error msg 

```
Argument of type 'import("C:/Users/kavis/demos/defi-stake-yield-brownie/front-end/node_modules/@ethersproject/contracts/lib/index").Contract' is not assignable to parameter of type 'import("C:/Users/kavis/demos/defi-stake-yield-brownie/front-end/node_modules/@usedapp/core/node_modules/@ethersproject/contracts/lib/index").Contract'.
```
I Fixed this issue for me by deleting the @ethersproject folder inside @usedapp folder .
I think you should add this to  the README file  as I could not figure out how to resolve this issue for some time

**Comment by nicolas-sanch** [comment]
Hi!
Following the youtube tutorial, when I try to:
 `yarn add @ethersproject/contract`
Terminal return: `error An unexpected error occurred: "https://registry.yarnpkg.com/@ethersproject%2fcontract: Not found"`

Also, if I delete @ethersproject from @usedapp folder as @kavish6, I have:
 `TypeError: Cannot read properties of undefined (reading '0')` 
For the line `const tokenFarmAddress = chainId ? networkMapping[String(chainId)]["TokenFarm"][0] : constants.AddressZero`

Any idea ?

**Comment by PatrickAlphaC** [comment]
Yes! We should add this to the chronological issues spot of the main repo....

Thanks both of you! Closing for now.
