### ISSUE TITLE
ConnectionError: HTTPSConnectionPool(host='api-kovan.etherscan.io', port=443):  WHY？？？？

### ISSUE THREAD

**Issue by tttonytan** [PatrickAlphaC/defi-stake-yield-brownie-freecode#10]
ConnectionError: HTTPSConnectionPool(host='api-kovan.etherscan.io', port=443): Max retries exceeded with url: /api?apikey=X7EP948CD2F8A86PDAHH7N9AC5VD8BYMDX&module=account&action=txlist&address=0x740fa2cc9992909A1B80ce816A45A42d248533C9&page=1&sort=asc&offset=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002A00E4683A0>: Failed to establish a new connection: [WinError 10060]

**Comment by PatrickAlphaC** [comment]
Thanks for making an issue, could we get some additional information? 

1. What was the command you ran?
2. What's your directory look like?
3. What does the contract look like?

**Comment by tttonytan** [comment]
It turns out that it is the ETHERSCAN_TOKEN in .env made this unexpectable error!
Thks Patric for help!
