### ISSUE TITLE
How to issue tokens to get the staking "reward"

### ISSUE THREAD

**Issue by mattheweller** [PatrickAlphaC/defi-stake-yield-brownie-freecode#13]
Ok, so I wired up the unstaking portion and got everything looking slick but for the life of me I couldn't figure out where/how to call the issueTokens function from the TokenFarm contract to "yield" my "reward" for "staking" my "tokens" in this "Dapp". I was just passing tokens to the contract and then having the contract hand me back my tokens... I did finally figure out that as the contract owner, I can call issueTokens manually right from [Etherscan](https://kovan.etherscan.io/address/0xed9ee785b32c7ce1ddf22dade9bc36cfe3107d23#writeContract)!

I guess alternatively we could have an issue_tokens function with the other python scripts. Can we please add a note to the readme or even a comment to the deploy.py file outlining the function so folks don't get hung up for as long as I did?

**Comment by PatrickAlphaC** [comment]
Great point! yes! this was a subset of the full functionality, I'll add more info to the readme. Thanks for this!
