### ISSUE TITLE
Not able to retrieve token balance

### ISSUE THREAD

**Issue by karthikr87** [PatrickAlphaC/defi-stake-yield-brownie-freecode#21]
The application is connected to the metamask wallet that is connected to the Kovan test network.
I am able to get all three token addresses but am not able to get the balances of them using the useTokenBalance method.
Even I cross-checked with your code on GitHub. Not finding any issues at all. Not Sure What I am doing wrong. 
Error msg: undefined.

**Comment by karthikr87** [comment]
version mismatch. Installed 0.7 of usedapp fixed the problem

**Comment by huaihsuanbusiness** [comment]
@achimstruve 
Same issue here, I cannot find and figure out the meaning of the third step "package.lock" that Patrick mentioned,
do you know where it is?

**Comment by achimstruve** [comment]
> @achimstruve 
> Same issue here, I cannot find and figure out the meaning of the third step a line called "package.lock" that Patrick mentioned,
> do you know where it is? 
> 

It is meant to be the `package.json` file in your `front_end` folder. Go into the file and change following line:
`"@usedapp/core": "0.4.2",`
