### ISSUE TITLE
No longer able to deploy contract to Kovan

### ISSUE THREAD

**Issue by jpernia101** [PatrickAlphaC/defi-stake-yield-brownie-freecode#26]
been following this tutorial but im not being able to deploy my contract anymore and i think it has to do with Kovan being depreciated. Is set to read only now so i dont think any transaction would go through.  not too sure tho since im pretty new to the space 
![image](https://user-images.githubusercontent.com/21113685/190154188-a04bbcce-dd3e-4a9c-b339-4f1870bd99ca.png)

**Comment by jpernia101** [comment]
also cloned the project and received the same error :/ . that sucks if that is the case.

**Comment by PatrickAlphaC** [comment]
Yeah :(

Kovan is dying :(
