### ISSUE TITLE
supportedChain is deprecated, please pass networks instead

### ISSUE THREAD

**Issue by SuperZooper3** [PatrickAlphaC/defi-stake-yield-brownie-freecode#6]
App.tsx uses `supportedChains: [ChainId.Kovan],` [here](https://github.com/PatrickAlphaC/defi-stake-yield-brownie-freecode/blob/0dd62b0be06a7c580a6da047ec018a302b20dd7b/front_end/src/App.tsx#L10).
When I use this same code snippet, I get my console bombarded with `supportedChain is deprecated, please pass networks instead` making debugging quite hard. I haven't been able to figure out how to fix it with "pass networks".

**Comment by PatrickAlphaC** [comment]
That's really annoying... can you just use a different version of usedapp for the time being?

1. Delete your `node_modules` folder
2. Delete your `yarn.lock`.
3. change the line `package.lock` to `"@usedapp/core": "0.4.2"`
4. Run `yarn` and then run everything.

**Comment by SuperZooper3** [comment]
For those who might stumble across this later, I figured it out:
1. Import Rinkeby or any other networks you need from usedapp/core `import { DAppProvider, Rinkeby} from '@usedapp/core';` 
2. In your DApp provider in the html, change it to `<DAppProvider config={{
      networks: [Rinkeby], whatever else you need}}>` 

This should ensure that you don't have a thousand messages a second in your console!

**Comment by PatrickAlphaC** [comment]
Oh nice!!

**Comment by AnneCh** [comment]
Hi @SuperZooper3 ,

I'm stuck at this exact spot, where my console only logs "undefined" and "dev".

I've tried what you did, and it doesn't work at all, it actually won't compile.
Is there anything else you had done? Had you change something in the Main file as well?

Thanks

**Comment by AnneCh** [comment]
I've also tried Patrick's solution, and it doesn't work either.
On top of that, I have an error message from ```const networkName = chainId ? helperConfig[chainId] : "dev"```

which says:
``` const chainId: ChainId
Element implicitly has an 'any' type because expression of type 'ChainId' can't be used to index type '{ "42": string; "4": string; "1337": string; "1": string; }'.
  Property '[ChainId.Ropsten]' does not exist on type '{ "42": string; "4": string; "1337": string; "1": string; }'.ts(7053)```
